version: '3.8'

services:
  analytics-dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=host.docker.internal
      - DB_NAME=data_warehouse
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - analytics-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: data_warehouse
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - analytics-network

volumes:
  postgres_data:

networks:
  analytics-network:
    driver: bridge